import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { AppContextProvider } from "./context/appcontext";
import { AuthContextProvider } from "./context/authcontext";
import { PeopleProvider } from "./context/peoplecontext";
import { StatisticsProvider } from "./context/statisticscontext";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <AuthContextProvider>
          <AppContextProvider>
            <StatisticsProvider>
              <PeopleProvider>  
                {children}
              </PeopleProvider>
            </StatisticsProvider>
          </AppContextProvider>
        </AuthContextProvider>
      </body>
    </html>
  );
}
